name: Security Checks

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout код
        uses: actions/checkout@v4

      - name: Установка Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl
          wget -qO- https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.tar.gz | tar zxvf - 
          sudo mv trivy /usr/local/bin/
          trivy --version  # Проверяем, что Trivy установлен

      - name: Проверка зависимостей
        run: trivy fs .

      - name: Проверка контейнера
        run: |
          docker build -t myapp .
          trivy image myapp
