name: Security Checks

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout код
        uses: actions/checkout@v4

      - name: Установка Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh
          sudo mv ./bin/trivy /usr/local/bin/trivy
          export PATH=$PATH:/usr/local/bin
          trivy --version  # Проверяем, что Trivy установлен

      - name: Проверка зависимостей
        run: trivy fs --exit-code 0 ./home/kali/devsecops-demo/

      - name: Проверка контейнера
        run: |
          docker build -t myapp .
          trivy image myapp
